#ifndef USBRELAY_PROTOCOL_H
#define USBRELAY_PROTOCOL_H

#define USBRELAY_DISCOVERY_PORT 3241
#define USBRELAY_PRINT_PORT 3242
#define USBRELAY_DISCOVERY_MAGIC "USBRELAY-DISCOVERY/1"
#define USBRELAY_PRINT_MAGIC "USBRELAY-PRINT/1"
#define USBRELAY_PORT_PREFIX L"USBRELAY:"
#define USBRELAY_PORT_MONITOR_NAME L"USBRelay Port Monitor"
#define USBRELAY_SERVICE_NAME L"USBRelayServer"
#define USBRELAY_SERVICE_NAME_A "USBRelayServer"
#define USBRELAY_CLIENT_TASK_NAME L"USBRelay-Client-Autostart"
#define USBRELAY_SERVER_TASK_NAME L"USBRelay-Server-Autostart"

#endif
